### PR TITLE
Fix deleteTable function

### PR DESCRIPTION
**Pull request by toru-takahashi**
API Spec it the following
Delete: POST /v3/table/delete/:database/:table

### CODE REVIEW

**Comment by Lewuathe** [comment]
@toru-takahashi Good catch! thanks. Could you add a spec if possible?
1. Define mock server endpoint like [here](https://github.com/treasure-data/td-client-node/blob/master/test/TDMockApi.js#L20-L22)
2. Access and verify correct result like [here](https://github.com/treasure-data/td-client-node/blob/master/test/td_mock_request_test.js#L35-L43).

**Comment by toru-takahashi** [comment]
ok.

**Comment by Lewuathe** [comment]
LGTM. Thanks!

**Comment by toru-takahashi** [comment]
Thanks!

2016-06-02 11:32 GMT+09:00 Kai Sasaki <notifications@github.com>:

> Merged #19 <https://github.com/treasure-data/td-client-node/pull/19>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/treasure-data/td-client-node/pull/19#event-679264420>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AD8dtw1tRw_7PrHbc18F8rBE99RTYzg0ks5qHkDbgaJpZM4IsI59>
> .
>



-- 
-------------------------------------------------------
Toru Takahashi
Support Engineering Manager
Treasure Data, Inc.

EMAIL: takahashi@treasure-data.com
To Support: support@treasure-data.com
WEB: http://www.treasure-data.com/
-------------------------------------------------------

**Pull request merged**
